# Generated by Django 2.1.5 on 2021-03-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=10)),
                ('predicted', models.BooleanField(default=False)),
            ],
        ),
    ]
