# Generated by Django 2.1.5 on 2021-04-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeprofile',
            name='assigned_mentor',
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorship.MentorProfile'),
        ),
    ]
