# Generated by Django 3.2 on 2021-05-16 13:19

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_auto_20210428_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=255, unique=True)),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=30)),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=150)),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='sex',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=255, unique=True)),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=30)),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=150)),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='sex',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
        ),
    ]
