# Generated by Django 3.2 on 2021-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_auto_20210516_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
    ]
