# Generated by Django 2.1.5 on 2021-02-21 11:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_remove_mentorprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='hear_about_us_other',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='hear_about_us',
            field=models.CharField(default='Word of mouth', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='intrests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
