# Generated by Django 2.1.5 on 2021-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_auto_20210221_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
