# Generated by Django 2.1.5 on 2021-02-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0007_auto_20210221_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='year_applied',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
