# Generated by Django 2.1.5 on 2021-02-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0008_auto_20210221_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menteeprofile',
            old_name='entrance_exam_experience',
            new_name='entrance_exam',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='interview_experience',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='universities',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='year_applied',
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='confidence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='help_needed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='preparation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='course',
            field=models.CharField(default='Medicine', max_length=255),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
    ]
