# Generated by Django 2.1.5 on 2021-02-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0009_auto_20210221_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='assigned_mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentee', to='mentorship.MentorProfile'),
        ),
    ]
