# Generated by Django 2.1.5 on 2021-03-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0016_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='predicted',
            field=models.BooleanField(default=False),
        ),
    ]
