"""
Django settings for acmm project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta

from csp.constants import NONE, SELF

from .env_config import BASE_DIR, env

DEBUG = env("DEBUG")

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django.contrib.sites",
    "django.contrib.flatpages",
    "crispy_forms",
    "crispy_bootstrap4",
    "axes",
    "csp",
    # OTP for admin only
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    "two_factor",
    "mentorship.apps.MentorshipConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "csp.middleware.CSPMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    "axes.backends.AxesStandaloneBackend",
    # Django ModelBackend is the default authentication backend.
    "django.contrib.auth.backends.ModelBackend",
]

ROOT_URLCONF = "acmm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "acmm.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_ROOT = "static"
STATIC_URL = "/static/"
STATICFILES_DIRS = []

# CRISPY Settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

# Flat page settings
SITE_ID = 1

# Admin site settings
ADMIN_URL = env("ADMIN_URL")
LOGIN_URL = "two_factor:login"
LOGIN_REDIRECT_URL = "two_factor:profile"

# AXES
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = None
AXES_LOCKOUT_PARAMETERS = ["ip_address", ["username", "user_agent"]]
AXES_VERBOSE = True
AXES_ENABLE_ACCESS_FAILURE_LOG = True


# OTP Settings
OTP_TOTP_ISSUER = "African Caribbean Medical Mentors"


# CSP settings
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        # Default: only your domain
        "default-src": [SELF],
        # JS sources
        "script-src": [
            SELF,
            "https://cdn.jsdelivr.net",
            "https://stackpath.bootstrapcdn.com",
        ],
        # CSS sources
        "style-src": [
            SELF,
            "https://cdn.jsdelivr.net",
            "https://stackpath.bootstrapcdn.com",
        ],
        # Images
        "img-src": [
            SELF,
            "data:",  # for inline images (e.g. base64)
        ],
        # Fonts (Bootstrap / Google fonts etc.)
        "font-src": [
            SELF,
            "https://fonts.gstatic.com",
        ],
        # API / AJAX calls
        "connect-src": [
            SELF,
        ],
        # Prevent clickjacking
        "frame-ancestors": [SELF],
        # Restrict form submissions
        "form-action": [SELF],
        # Block plugins (Flash etc.)
        "object-src": ["'none'"],
        # Optional but recommended
        "base-uri": [SELF],
        # Reporting endpoint
        "report-uri": "/csp-report/",
    }
}


ADMINS = [x.split(":") for x in env.list("DJANGO_ADMINS")]
