# Generated by Django 6.0.3 on 2026-04-19 12:43

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenteeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personal_email",
                    encrypted_fields.fields.EncryptedEmailField(max_length=254),
                ),
                (
                    "work_email",
                    encrypted_fields.fields.EncryptedEmailField(max_length=254),
                ),
                (
                    "first_name",
                    encrypted_fields.fields.EncryptedCharField(max_length=30),
                ),
                (
                    "last_name",
                    encrypted_fields.fields.EncryptedCharField(max_length=130),
                ),
                ("number", encrypted_fields.fields.EncryptedCharField(max_length=130)),
                (
                    "year_applied",
                    models.CharField(
                        choices=[
                            ("A2", "A level/IB"),
                            ("GRAD", "Graduate"),
                            ("OT", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "entrance_exam_experience",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("BMAT", "BMAT"),
                                ("UCAT", "UCAT"),
                                ("GAMSAT", "GAMSAT"),
                            ],
                            max_length=10,
                        )
                    ),
                ),
                (
                    "interview_experience",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("P", "Panel"), ("M", "MMI"), ("G", "Group")],
                            max_length=1,
                        )
                    ),
                ),
                (
                    "area_of_support",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("PS", "Personal Statement"),
                                ("I", "Interview"),
                                ("EE", "Entrance Exam"),
                                ("WE", "Work Experience"),
                            ],
                            max_length=2,
                        )
                    ),
                ),
                (
                    "wp_scheme",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "applied_before",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "contact_consent",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "tcs_consent",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "hear_about_us",
                    models.CharField(
                        choices=[
                            ("WM", "Word of mouth"),
                            ("C", "Contact from ACMM team"),
                            ("SM", "Social Media"),
                            ("SU", "School/University"),
                            ("E", "Employer"),
                            ("OT", "Other"),
                        ],
                        default=None,
                        max_length=2,
                    ),
                ),
                ("mentor_need", models.TextField()),
                ("mentor_help", models.TextField()),
                ("mentor_relationship", models.TextField()),
                (
                    "course",
                    models.CharField(
                        choices=[("M", "Medicine"), ("D", "Dentistry")], max_length=1
                    ),
                ),
                (
                    "current_application",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "commitment",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "state_educated",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "family_support",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personal_email",
                    encrypted_fields.fields.EncryptedEmailField(max_length=254),
                ),
                (
                    "work_email",
                    encrypted_fields.fields.EncryptedEmailField(max_length=254),
                ),
                (
                    "first_name",
                    encrypted_fields.fields.EncryptedCharField(max_length=30),
                ),
                (
                    "last_name",
                    encrypted_fields.fields.EncryptedCharField(max_length=130),
                ),
                ("number", encrypted_fields.fields.EncryptedCharField(max_length=130)),
                (
                    "year_applied",
                    models.CharField(
                        choices=[
                            ("A2", "A level/IB"),
                            ("GRAD", "Graduate"),
                            ("OT", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "entrance_exam_experience",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("BMAT", "BMAT"),
                                ("UCAT", "UCAT"),
                                ("GAMSAT", "GAMSAT"),
                            ],
                            max_length=10,
                        )
                    ),
                ),
                (
                    "interview_experience",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("P", "Panel"), ("M", "MMI"), ("G", "Group")],
                            max_length=1,
                        )
                    ),
                ),
                (
                    "area_of_support",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("PS", "Personal Statement"),
                                ("I", "Interview"),
                                ("EE", "Entrance Exam"),
                                ("WE", "Work Experience"),
                            ],
                            max_length=2,
                        )
                    ),
                ),
                (
                    "wp_scheme",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "applied_before",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "contact_consent",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "tcs_consent",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "hear_about_us",
                    models.CharField(
                        choices=[
                            ("WM", "Word of mouth"),
                            ("C", "Contact from ACMM team"),
                            ("SM", "Social Media"),
                            ("SU", "School/University"),
                            ("E", "Employer"),
                            ("OT", "Other"),
                        ],
                        default=None,
                        max_length=2,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("MD", "Doctor"),
                            ("D", "Dentist"),
                            ("MS", "Medical Student"),
                            ("DS", "Dental Student"),
                        ],
                        max_length=2,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "additional_info",
                    models.TextField(blank=True, default="", null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MenteeQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("A2", "A Level"),
                            ("AS", "A/S Level"),
                            ("IB", "International Baccalaureate"),
                            ("SH", "Scottish Highers and Advanced Highers"),
                            ("UG", "Undergraduate"),
                            ("M", "Masters"),
                            ("D", "Doctorate"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A*", "A*"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("1st", "1st"),
                            ("2:1", "2:1"),
                            ("2:2", "2:2"),
                            ("3rd", "3rd"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "predicted",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.menteeprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menteeprofile",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mentorship.mentorprofile",
            ),
        ),
    ]
