# Generated by Django 6.0.3 on 2026-04-12 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenteeQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("A2", "A Level"),
                            ("AS", "A/S Level"),
                            ("IB", "International Baccalaureate"),
                            ("SH", "Scottish Highers and Advanced Highers"),
                            ("UG", "Undergraduate"),
                            ("M", "Masters"),
                            ("D", "Doctorate"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A*", "A*"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("1st", "1st"),
                            ("2:1", "2:1"),
                            ("2:2", "2:2"),
                            ("3rd", "3rd"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "predicted",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mentorship.menteeprofile",
                    ),
                ),
            ],
        ),
    ]
