# Generated by Django 6.0.3 on 2026-04-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menteeprofile",
            name="hear_about_us",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WM", "Word of mouth"),
                    ("C", "Contact from ACMM team"),
                    ("SM", "Social Media"),
                    ("SU", "School/University"),
                    ("E", "Employer"),
                    ("OT", "Other"),
                ],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="hear_about_us",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WM", "Word of mouth"),
                    ("C", "Contact from ACMM team"),
                    ("SM", "Social Media"),
                    ("SU", "School/University"),
                    ("E", "Employer"),
                    ("OT", "Other"),
                ],
                default=None,
                max_length=2,
                null=True,
            ),
        ),
    ]
