# Generated by Django 2.0.1 on 2021-02-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as an mentor. ', verbose_name='mentor status'),
        ),
    ]
