# Generated by Django 4.0.4 on 2022-06-08 20:37

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='work_email',
            field=django_cryptography.fields.encrypt(models.EmailField(default='hello@nhs.co.uk', max_length=254)),
            preserve_default=False,
        ),
    ]
