# Generated by Django 2.1.5 on 2021-02-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='location',
        ),
    ]
