# Generated by Django 6.0.3 on 2026-04-12 13:18

import django.contrib.postgres.fields
import django.utils.timezone
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0002_menteequalification"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personal_email",
                    encrypted_fields.fields.EncryptedEmailField(max_length=254),
                ),
                (
                    "first_name",
                    encrypted_fields.fields.EncryptedCharField(max_length=30),
                ),
                (
                    "last_name",
                    encrypted_fields.fields.EncryptedCharField(max_length=130),
                ),
                ("number", encrypted_fields.fields.EncryptedCharField(max_length=130)),
                (
                    "year_applied",
                    models.CharField(
                        choices=[
                            ("A2", "A level/IB"),
                            ("GRAD", "Graduate"),
                            ("OT", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "entrance_exam_experience",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("BMAT", "BMAT"),
                                ("UCAT", "UCAT"),
                                ("GAMSAT", "GAMSAT"),
                            ],
                            max_length=10,
                        )
                    ),
                ),
                (
                    "interview_experience",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[("P", "Panel"), ("M", "MMI"), ("G", "Group")],
                            max_length=1,
                        )
                    ),
                ),
                (
                    "area_of_support",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("PS", "Personal Statement"),
                                ("I", "Interview"),
                                ("EE", "Entrance Exam"),
                                ("WE", "Work Experience"),
                            ],
                            max_length=2,
                        )
                    ),
                ),
                (
                    "wp_scheme",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "applied_before",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "contact_consent",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "terms_policy_consent",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "hear_about_us",
                    models.CharField(
                        choices=[
                            ("WM", "Word of mouth"),
                            ("C", "Contact from ACMM team"),
                            ("SM", "Social Media"),
                            ("SU", "School/University"),
                            ("E", "Employer"),
                            ("OT", "Other"),
                        ],
                        default=None,
                        max_length=2,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("MD", "Doctor"),
                            ("D", "Dentist"),
                            ("MS", "Medical Student"),
                            ("DS", "Dental Student"),
                        ],
                        max_length=2,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "additional_info",
                    models.TextField(blank=True, default="", null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
