# Generated by Django 2.0.1 on 2021-02-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_auto_20210214_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mentee',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a mentee. ', verbose_name='mentee status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a mentor. ', verbose_name='mentor status'),
        ),
    ]
