# Generated by Django 6.0.3 on 2026-04-12 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorship", "0003_mentorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="menteeprofile",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mentorship.mentorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="mentorprofile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
