# Generated by Django 2.0.1 on 2021-02-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_auto_20210214_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'mentor'), (2, 'mentee')])),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mentee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mentor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
