# Generated by Django 2.0.1 on 2021-02-14 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_auto_20210214_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_interest1', models.CharField(choices=[('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Scientist', 'Scientist'), ('Biologist', 'Biologist'), ('Business', 'Business')], default='Doctor', max_length=30)),
                ('career_interest2', models.CharField(choices=[('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Scientist', 'Scientist'), ('Biologist', 'Biologist'), ('Business', 'Business')], default='Doctor', max_length=30)),
                ('career_interest3', models.CharField(choices=[('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Scientist', 'Scientist'), ('Biologist', 'Biologist'), ('Business', 'Business')], default='Doctor', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_expertise1', models.CharField(choices=[('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Scientist', 'Scientist'), ('Biologist', 'Biologist'), ('Business', 'Business'), ('--', '--')], default='--', max_length=30)),
                ('career_expertise2', models.CharField(choices=[('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Scientist', 'Scientist'), ('Biologist', 'Biologist'), ('Business', 'Business'), ('--', '--')], default='--', max_length=30)),
                ('career_expertise3', models.CharField(choices=[('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Scientist', 'Scientist'), ('Biologist', 'Biologist'), ('Business', 'Business'), ('--', '--')], default='--', max_length=30)),
                ('career_expertise4', models.CharField(choices=[('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Scientist', 'Scientist'), ('Biologist', 'Biologist'), ('Business', 'Business'), ('--', '--')], default='--', max_length=30)),
                ('career_expertise5', models.CharField(choices=[('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Scientist', 'Scientist'), ('Biologist', 'Biologist'), ('Business', 'Business'), ('--', '--')], default='--', max_length=30)),
                ('career_expertise6', models.CharField(choices=[('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer'), ('Scientist', 'Scientist'), ('Biologist', 'Biologist'), ('Business', 'Business'), ('--', '--')], default='--', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='user',
            name='is_mentee',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a mentor. ', verbose_name='mentor status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a mentor. ', verbose_name='mentor status'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
