# Generated by Django 2.0.1 on 2021-02-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_auto_20210214_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_mentee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mentor',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as staff. ', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mentor'), (2, 'Mentee')], null=True),
        ),
    ]
