# Generated by Django 2.0.1 on 2021-02-14 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0006_auto_20210214_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='career_interest2',
        ),
        migrations.RemoveField(
            model_name='menteeprofile',
            name='career_interest3',
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='career_interest1',
            field=models.CharField(choices=[('Doctor', 'Doctor')], default='Doctor', max_length=30),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MentorProfile',
        ),
    ]
