# Generated by Django 2.0.1 on 2021-02-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0007_auto_20210214_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='MenteeProfile',
        ),
    ]
