# Generated by Django 2.0.1 on 2021-02-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0008_auto_20210214_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
