# Generated by Django 2.1.5 on 2021-03-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0011_auto_20210221_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='location',
        ),
    ]
