# Generated by Django 2.1.5 on 2021-03-06 11:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0012_remove_mentorprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='specialty',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
