# Generated by Django 2.1.5 on 2021-03-06 12:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0013_auto_20210306_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='application_strength',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
