# Generated by Django 2.1.5 on 2021-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0013_auto_20210220_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='areas_of_intrest',
            field=models.CharField(choices=[('Outreach Programmes', 'Outreach Programmes'), ('Speaking at events', 'Speaking at events'), ('Support for events', 'Support for events'), ('Provision of work experience/volunteering opportunities', 'Provision of work experience/volunteering opportunities'), ('Additional guidance for mentors (one off)', 'Additional guidance for mentors (one off)')], default='Doctor', max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='current_occupation',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Dentist', 'Dentist'), ('Medical Student', 'Medical Student'), ('Graduate Medical Student', 'Graduate Medical Student'), ('Medical Student Studying Abroad', 'Medical Student Studying Abroad'), ('Dental student', 'Dental student')], default='Doctor', max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='position_specialty',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
