# Generated by Django 2.1.5 on 2021-02-20 16:06

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0014_auto_20210220_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='hear_about_us',
            field=models.CharField(choices=[('Outreach Programmes', 'Outreach Programmes'), ('Speaking at events', 'Speaking at events'), ('Support for events', 'Support for events'), ('Provision of work experience/volunteering opportunities', 'Provision of work experience/volunteering opportunities'), ('Additional guidance for mentors (one off)', 'Additional guidance for mentors (one off)')], default='Word of mouth', max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='hear_about_us_other',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='location',
            field=django_countries.fields.CountryField(default='N/A', max_length=2),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='year_of_study',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
