# Generated by Django 2.1.5 on 2021-03-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0014_mentorprofile_application_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='application_strength',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
