# Generated by Django 2.1.5 on 2021-02-20 16:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0015_auto_20210220_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name="Mentee's email address")),
                ('first_name', models.CharField(max_length=30, verbose_name="Mentee's first name")),
                ('last_name', models.CharField(max_length=30, verbose_name="Mentee's last name")),
                ('entrance_exam_experience', multiselectfield.db.fields.MultiSelectField(choices=[('BMAT', 'BMAT'), ('UKCAT', 'UKCAT'), ('GAMSAT', 'GAMSAT')], max_length=17)),
                ('interview_experience', multiselectfield.db.fields.MultiSelectField(choices=[('BMAT', 'BMAT'), ('UKCAT', 'UKCAT'), ('GAMSAT', 'GAMSAT')], max_length=17)),
                ('subjects', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='areas_of_intrest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Outreach Programmes', 'Outreach Programmes'), ('Speaking at events', 'Speaking at events'), ('Support for events', 'Support for events'), ('Provision of work experience/volunteering opportunities', 'Provision of work experience/volunteering opportunities'), ('Additional guidance for mentors (one off)', 'Additional guidance for mentors (one off)')], max_length=155),
        ),
    ]
